#print("Hola mundo".startswith("Hola"))
#print("abc123".isdigit())
#print("1234".isnumeric())
#print("hola mundo".capitalize())
#print("Hola mundo".replace("Hola", "Hello"))
#print("Hola Mundo!".upper())
#print("Hola".center(20, "*"))
print(", ".join(["C", "C++", "Python", "Java"]))